controller_list:
  - name: fake_arm_controller
    joints:
      - rbkairos_a_arm_shoulder_pan_joint
      - rbkairos_a_arm_shoulder_lift_joint
      - rbkairos_a_arm_elbow_joint
      - rbkairos_a_arm_wrist_1_joint
      - rbkairos_a_arm_wrist_2_joint
      - rbkairos_a_arm_wrist_3_joint
  - name: fake_eef_1_controller
    joints:
      []