sensors:
- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: front_rgbd_camera/depth/points
  max_range: 4.0
  frame_subsample: 1
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.0
  
