# !/bin/bash

MAP=model5
NROBOTS=1
ALG_SHORT=CYCLE
LOC_MODE=odom
GWAIT=0
COMMDELAY=0.2
TERM=gnome-terminal 
TIMEOUT=1800
MASTER=true
FROM=0
TO=1
NETWORK_IF=lo
ROBOT=real
CAPACITY=2

./start_experiment_distributed.py $MAP $NROBOTS $ALG_SHORT $LOC_MODE $GWAIT $COMMDELAY $TERM $TIMEOUT $MASTER $FROM $TO $NETWORK_IF $ROBOT $CAPACITY